kind: PersistentVolume
apiVersion: v1
metadata:
  name: local-pv
  namespace: wordpress
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/data
