apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
  namespace: wordpress

spec:
  hard:
    pods: "5"
    requests.cpu: "500m"
    requests.memory: "500Mi"
    limits.cpu: "1"
    limits.memory: "1Gi"
    secrets: "5"
